import type { Item } from "@/lib/types";

export const seedItems: Item[] = [
  {
    id: "seed-1",
    created_at: new Date().toISOString(),
    item_name: "Waxed Canvas Jacket",
    brand: "Flint & Tinder",
    category: "Outerwear",
    condition: "Very good",
    purchase_price: 42,
    target_sale_price: 128,
    platform: "eBay",
    status: "listed",
    sku: "FLIJAC-1842",
    storage_location: "Rack A",
    notes: "Minor sleeve wear. Great fall listing.",
    estimated_resale_low: 110,
    estimated_resale_high: 145,
    max_buy_price: 61.2,
    deal_score: 62,
    deal_recommendation: "Strong buy",
    facebook_listing: "",
    ebay_listing: "",
    poshmark_listing: "",
    sold_price: null,
    shipping_cost: null,
    fees: null,
    net_profit: null,
  },
  {
    id: "seed-2",
    created_at: new Date().toISOString(),
    item_name: "Leather Chelsea Boots",
    brand: "Thursday",
    category: "Shoes",
    condition: "Good",
    purchase_price: 36,
    target_sale_price: 96,
    platform: "Poshmark",
    status: "draft",
    sku: "THUCHE-9021",
    storage_location: "Bin 3",
    notes: "Needs quick polish before photos.",
    estimated_resale_low: 82,
    estimated_resale_high: 115,
    max_buy_price: 47.28,
    deal_score: 58,
    deal_recommendation: "Buy if condition checks out",
    facebook_listing: "",
    ebay_listing: "",
    poshmark_listing: "",
    sold_price: null,
    shipping_cost: null,
    fees: null,
    net_profit: null,
  },
  {
    id: "seed-3",
    created_at: new Date().toISOString(),
    item_name: "Vintage Brass Lamp",
    brand: "Unbranded",
    category: "Home",
    condition: "Excellent",
    purchase_price: 18,
    target_sale_price: 74,
    platform: "Facebook Marketplace",
    status: "sold",
    sku: "UNBLAM-4410",
    storage_location: "Sold shelf",
    notes: "Local pickup sale.",
    estimated_resale_low: 60,
    estimated_resale_high: 85,
    max_buy_price: 34.8,
    deal_score: 72,
    deal_recommendation: "Strong buy",
    facebook_listing: "",
    ebay_listing: "",
    poshmark_listing: "",
    sold_price: 70,
    shipping_cost: 0,
    fees: 3,
    net_profit: 49,
  },
];
